[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
balls_bond = "UreL6sVKo1EgsyLwwhGL6gBKA3V3zTDb2YC7Z3bALLs"

[programs.devnet]
balls_bond = "UreL6sVKo1EgsyLwwhGL6gBKA3V3zTDb2YC7Z3bALLs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
